### ISSUE TITLE
module 'board' has no attribute 'NEOPIXEL'

### ISSUE THREAD

**Issue by neramas1221** [adafruit/Adafruit_CircuitPython_NeoPixel#84]
Hi there! I tried one of the example and i got this error, i tried searching online but i couldnt find a solution. What could be causing this?

File "neopixesl_test.py", line 8, in <module>
    pixel_pin = board.NEOPIXEL
AttributeError: module 'board' has no attribute 'NEOPIXEL'

Thank you for any help!

**Comment by siddacious** [comment]
`board.NEOPIXEL` is an alias created for boards that have a built in NeoPixel for the pin that should be used to control the built in one. If you're getting this error it's because your board doesn't have one built in!  

See this guide page for more information on interfacing with NeoPixels:
https://learn.adafruit.com/circuitpython-essentials/circuitpython-neopixel

Github issues are for reporting bugs or making feature requests, not for support. If you have more questions, ask them in the CircuitPython and MicroPython forum:
https://forums.adafruit.com/viewforum.php?f=60
